### ISSUE TITLE
Secure endpoints

### ISSUE THREAD

**Issue by yreaction** [Friend-LGA/LGConnection#1]
Your repos are neat LGA, but for this one I miss the important feature for set the header of the managers for secure endpoints. There is no way to set headers as "Token".

**Comment by Friend-LGA** [comment]
This is simple library that I wrote, because AFNetworking didn't parse XML by default. It doesn't have a lot of abilities and if you really want to use it, you can make pull request to improve functionality. I don't have a lot of free time to update it now.

By the way in this method:

``` objective-c
- (void)sendRequestToUrl:(NSURL *)url
                  method:(LGConnectionMethod)method
              parameters:(id)parameters
            responseType:(LGConnectionResponseType)responseType
            setupHandler:(void(^)(AFHTTPRequestOperationManager *manager))setupHandler
       completionHandler:(void(^)(NSError *error, id responseObject))completionHandler;
```

you can do everything you want with manager in `setupHandler`

**Comment by yreaction** [comment]
Already did it, thanks mate!
